---
name: accessors
version: 1.01
author:
  - 'Steve Purkis <spurkis@cpan.org>'
abstract: create accessor methods in caller's package.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.6.0
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
provides:
  accessors:
    file: lib/accessors.pm
    version: 1.01
  accessors::chained:
    file: lib/accessors/chained.pm
    version: 1.01
  accessors::classic:
    file: lib/accessors/classic.pm
    version: 1.01
  accessors::ro:
    file: lib/accessors/ro.pm
    version: 1.01
  accessors::rw:
    file: lib/accessors/rw.pm
    version: 1.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
