--- #YAML:1.0
name: accessors
version: 0.02
license: perl
distribution_type: module
requires:
  perl: 5.6.0
recommends: {}
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
conflicts: {}
provides:
  accessors:
    file: lib/accessors.pm
    version: 0.02
  accessors::chained:
    file: lib/accessors/chained.pm
    version: 0.02
  accessors::classic:
    file: lib/accessors/classic.pm
    version: 0.02
generated_by: Module::Build version 0.20
